services:
  clients:
    image: kimmi1206/alianza-prueba-springboot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - database
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8080:8080"
    environment:
      - 'POSTGRES_HOST=database'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=alianzaclients'

  database:
    image: 'postgres:latest'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=alianzaclients'
