spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/alianzaclients
  #  username: ${PGUSERNAME}
  #  password: ${PGPASSWORD}
  #  url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDBNAME}

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format_sql: true